networks:
  fiscalization-network:
    driver: bridge
  broker-network:
    driver: bridge
  loan-network:
    driver: bridge
  user-network:
    driver: bridge
  subsidy-network:
    driver: bridge

volumes:
  fiscalization-db-data:
  user-db-data:
  loan-db-data:
  subsidy-db-data:

services:
  zookeeper:
    image: confluentinc/cp-zookeeper
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - broker-network

  broker:
    image: confluentinc/cp-kafka
    container_name: broker
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    networks:
      - broker-network
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT, PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092

  loan-listener:
    build: ./loanlistener
    container_name: loan-listener
    depends_on:
      - broker
    ports:
      - "8181:8080"
    networks:
      - broker-network
      - loan-network
    environment:
      KAFKA_KAFKA_TOPIC: 'loan.published'
      SPRING_KAFKA_BOOTSTRAP_SERVERS: 'broker:9092'

  fiscalization-db:
    image: postgres:14
    environment:
      POSTGRES_DB: fiscalization
      POSTGRES_USER: user
      POSTGRES_PASSWORD: userpass
    volumes:
      - fiscalization-db-data:/var/lib/postgresql/data
    networks:
      - fiscalization-network
      - broker-network
    ports:
      - "5432:5432"

  fiscalization-listener:
    build: ./fiscalization-listener
    container_name: fiscalization-listener
    depends_on:
      - broker
      - fiscalization-db
    ports:
      - "8282:8080"
    environment:
      KAFKA_KAFKA_TOPIC: 'receipt.fiscalize'
      SPRING_KAFKA_BOOTSTRAP_SERVERS: 'broker:9092'
    networks:
      - fiscalization-network
      - broker-network

  api-gateway:
    build: ./gateway
    container_name: api-gateway
    depends_on:
      - broker
      - fiscalization-db
      - loan-db
      - user-db
    ports:
      - "8080:8080"
    networks:
      - broker-network
      - fiscalization-network
      - user-network
      - loan-network
    environment:
      LOANS_KAFKA_TOPIC: 'loan.published'
      LOANS_MICROSERVICE_URL: 'http://loan-listener:8080'
      FISCALIZATION_MICROSERVICE_URL: 'http://fiscalization-listener:8080'
      SUBSIDY_MICROSERVICE_URL: 'http://subsidy-listener:8080'
      FISCALIZE_KAFKA_TOPIC: 'receipt.fiscalize'
      SPRING_KAFKA_BOOTSTRAP_SERVERS: 'broker:9092'
  user-db:
    image: postgres:14
    environment:
      POSTGRES_DB: users
      POSTGRES_USER: user
      POSTGRES_PASSWORD: userpass
    volumes:
      - user-db-data:/var/lib/postgresql/data
    networks:
      - user-network
      - broker-network
    ports:
      - "5433:5432"

  user-listener:
    build: ./user-listener
    container_name: user-listener
    depends_on:
      - broker
      - user-db
    ports:
      - "8383:8080"
    environment:
      KAFKA_KAFKA_TOPIC: 'user.published'
      SPRING_KAFKA_BOOTSTRAP_SERVERS: 'broker:9092'
    networks:
      - user-network
      - broker-network

  loan-db:
    image: postgres:14
    environment:
      POSTGRES_DB: loans
      POSTGRES_USER: user
      POSTGRES_PASSWORD: userpass
    volumes:
      - loan-db-data:/var/lib/postgresql/data
    networks:
      - loan-network
      - broker-network
    ports:
      - "5434:5432"

  subsidy-listener:
    build: ./subsidy-listener
    container_name: subsidy-listener
    depends_on:
      - broker
      - subsidy-db
    ports:
      - "8484:8080"
    environment:
      KAFKA_KAFKA_TOPIC: 'subsidy.published'
      SPRING_KAFKA_BOOTSTRAP_SERVERS: 'broker:9092'
    networks:
      - subsidy-network
      - broker-network

  subsidy-db:
    image: postgres:14
    environment:
      POSTGRES_DB: subsidies
      POSTGRES_USER: user
      POSTGRES_PASSWORD: userpass
    volumes:
      - subsidy-db-data:/var/lib/postgresql/data
    networks:
      - subsidy-network
      - broker-network
    ports:
      - "5435:5432"