services:
  zookeeper:
    image: confluentinc/cp-zookeeper
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka
    container_name: broker
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT, PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092

  loan-listener:
    build: ./loanlistener
    container_name: loan-listener
    depends_on:
      - broker
    ports:
      - "8181:8080"
    environment:
      KAFKA_KAFKA_TOPIC: 'loan.published'
      SPRING_KAFKA_BOOTSTRAP_SERVERS: 'broker:9092'

  fiscalization-listener:
    build: ./fiscalization-listener
    container_name: fiscalization-listener
    depends_on:
      - broker
    ports:
      - "8282:8080"
    environment:
      KAFKA_KAFKA_TOPIC: 'receipt.fiscalize'
      SPRING_KAFKA_BOOTSTRAP_SERVERS: 'broker:9092'

  api-gateway:
    build: ./gateway
    container_name: api-gateway
    depends_on:
      - broker
    ports:
      - "8080:8080"
    environment:
      LOANS_KAFKA_TOPIC: 'loan.published'
      FISCALIZE_KAFKA_TOPIC: 'receipt.fiscalize'
      SPRING_KAFKA_BOOTSTRAP_SERVERS: 'broker:9092'